---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: purpleos
description: Custom Bluefin-DX image.

base-image: ghcr.io/ublue-os/bluefin-dx
image-version: stable-daily 

modules:
  - type: files
    files:
      - source: system
        destination: / 

  - type: rpm-ostree
    repos:
      # Remote URLs and local files (from files/rpm-ostree/) can be mixed here
      - https://brave-browser-rpm-beta.s3.brave.com/brave-browser-beta.repo
      - https://packages.freedom.press/yum-tools-prod/dangerzone/dangerzone.repo
      - protonvpn.repo
    install:
      - brave-origin-beta
      - proton-vpn-gnome-desktop
      - https://updates.safing.io/latest/linux_amd64/packages/Portmaster-2.1.18-1.x86_64.rpm
      - dangerzone
    remove:
      - tailscale

  - type: default-flatpaks
    configurations:
      - notify: true 
        scope: system
        install: 
          - org.videolan.VLC
  
  - type: systemd
    system:
      enabled:
        # This guarantees Portmaster starts automatically on boot
        - portmaster.service

  - type: signing 
